import unittest
from sha1 import sha1
import hashlib as hs

# 100 Random phrases regenerated with Mistral AI [https://mistral.ai/en]
random_phrases = [
    "A stitch in time saves nine",
    "Actions speak louder than words",
    "All that glitters is not gold",
    "An apple a day keeps the doctor away",
    "Barking up the wrong tree",
    "Beat around the bush",
    "Beggars can't be choosers",
    "Bite the bullet",
    "Break a leg",
    "Burning the midnight oil",
    "Call it a day",
    "Cat got your tongue?",
    "Costs an arm and a leg",
    "Cry over spilled milk",
    "Curiosity killed the cat",
    "Cut corners",
    "Don't count your chickens before they hatch",
    "Don't put all your eggs in one basket",
    "Every cloud has a silver lining",
    "Fit as a fiddle",
    "Get out of hand",
    "Give the benefit of the doubt",
    "Go the extra mile",
    "Hang in there",
    "Hit the books",
    "Hit the nail on the head",
    "In the nick of time",
    "It takes two to tango",
    "Kill two birds with one stone",
    "Knock on wood",
    "Let the cat out of the bag",
    "Make a long story short",
    "Method to my madness",
    "Miss the boat",
    "Once in a blue moon",
    "On the ball",
    "Piece of cake",
    "Play it by ear",
    "Pull someone's leg",
    "Read between the lines",
    "Ring a bell",
    "See eye to eye",
    "Sit tight",
    "Speak of the devil",
    "Spill the beans",
    "Take it easy",
    "Talk the talk",
    "The ball is in your court",
    "The best of both worlds",
    "The elephant in the room",
    "The plot thickens",
    "Time flies when you're having fun",
    "Under the weather",
    "Up in the air",
    "We'll cross that bridge when we come to it",
    "When it rains, it pours",
    "When pigs fly",
    "Wild goose chase",
    "You can say that again",
    "Your guess is as good as mine",
    "Achilles' heel",
    "Add insult to injury",
    "Against all odds",
    "All talk and no action",
    "Bamboozled",
    "Bark is worse than his bite",
    "Beating a dead horse",
    "Bend over backwards",
    "Best thing since sliced bread",
    "Bite the dust",
    "Blind leading the blind",
    "Break the ice",
    "Burst your bubble",
    "Caught between a rock and a hard place",
    "Checkered past",
    "Clean as a whistle",
    "Clear as mud",
    "Costs an arm and a leg",
    "Crack of dawn",
    "Cry wolf",
    "Dead as a doornail",
    "Devil's advocate",
    "Don't judge a book by its cover",
    "Down to the wire",
    "Every dog has its day",
    "Fair-weather friend",
    "Fall on deaf ears",
    "Feeling blue",
    "Few and far between",
    "Fool's gold",
    "For the birds",
    "Get your act together",
    "Give someone the cold shoulder",
    "Good things come to those who wait",
    "Happy as a clam",
    "Hard pill to swallow",
    "Head over heels",
    "Hit the sack",
    "In the doghouse",
    "It's not rocket science",
    "Jump on the bandwagon",
    "Keep your chin up",
    "Kick the bucket",
    "Kill time",
    "Last straw",
    "Let sleeping dogs lie",
    "Like a kid in a candy store",
    "Long time no see",
    "Miss the mark",
    "My way or the highway",
    "Needle in a haystack",
    "No pain, no gain",
    "Off the top of my head",
    "Old as the hills",
    "On the fence",
    "Out of the frying pan, into the fire",
    "Pain in the neck",
    "Piece of cake",
    "Play hard to get",
    "Pulling your leg",
    "Raining cats and dogs",
    "Read my lips",
    "Red herring",
    "Roll with the punches",
    "Seeing is believing",
    "Sitting on the fence",
    "Six feet under",
    "Speak of the devil",
    "Spill the beans",
    "Take a rain check",
    "The apple doesn't fall far from the tree",
    "The writing is on the wall",
    "Throw caution to the wind",
    "Time will tell",
    "Under the radar",
    "Up for grabs",
    "When it rains, it pours",
    "Wild goose chase",
    "You can't have your cake and eat it too",
    "Your guess is as good as mine"
]


class MyTestCase(unittest.TestCase):
    def test_sha1(self):
        for phrase in random_phrases:
            self.assertEqual(sha1(phrase.encode("utf-8")), hs.sha1(phrase.encode("utf-8")).hexdigest())


if __name__ == '__main__':
    unittest.main()
